### ISSUE TITLE
想请问下你的 isDelete 这个变量的命名是什么含义呢

### ISSUE THREAD

**Issue by w4mxl** [AnleSu/image_picker_demo#1]
https://github.com/AnleSu/image_picker_demo/blob/7e95341f0af99696106f716485695a45679bb0a2/image_picker_demo/lib/yz_imagePicker.dart#L105

我能通过对你的代码的整体理解，你是想在删除已经达到最大图片数目时的最后一张图之后，再添加一个含+号标示的item，我的理解是，这样应该需要的是一个是否已经添加过+号标示的item的变量，所以对 isDelete 的命名有点奇怪，可以的话，希望可以解答一下，谢谢  😅

**Comment by AnleSu** [comment]
isDelete 是用来标记 含+号的item 是否需要显示的
1.如果添加图片数超过maxCount ，isDelete设置为false，不需要显示含+号的item
2.如果有删除操作，则需要再把含+号的item显示出来，isDelete设置为true;

主要是用来判断加到maxCount再删除时候的临界条件

**Comment by w4mxl** [comment]
好的，谢谢解答
